#Preprocessing

In [ ]:
!pip install autokeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: autokeras in /usr/local/lib/python3.10/dist-packages (1.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from autokeras) (23.1)
Requirement already satisfied: tensorflow>=2.8.0 in /usr/local/lib/python3.10/dist-packages (from autokeras) (2.12.0)
Requirement already satisfied: keras-tuner>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from autokeras) (1.3.5)
Requirement already satisfied: keras-nlp>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from autokeras) (0.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from autokeras) (1.5.3)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from keras-nlp>=0.4.0->autokeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras-nlp>=0.4.0->autokeras) (1.22.4)
Requirement already satisfied: tensorflow-text in /usr/local/lib/python3.10/dist-packages (from keras-nlp>=0.4.0->autokeras) (2.12.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner>=1.1.0->autokeras) (2.27.1)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.10/dist-packages (from keras-tuner>=1.1.0->autokeras) (1.0.5)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (1.54.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (0.4.8)
Requirement already satisfied: keras<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (2.12.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (16.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (1.16.0)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (2.12.2)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (2.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.8.0->autokeras) (0.32.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->autokeras) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->autokeras) (2022.7.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=2.8.0->autokeras) (0.40.0)
Requirement already satisfied: ml-dtypes>=0.0.3 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow>=2.8.0->autokeras) (0.1.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow>=2.8.0->autokeras) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (3.4.3)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (2.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner>=1.1.0->autokeras) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner>=1.1.0->autokeras) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner>=1.1.0->autokeras) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner>=1.1.0->autokeras) (3.4)
Requirement already satisfied: tensorflow-hub>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow-text->keras-nlp>=0.4.0->autokeras) (0.13.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow>=2.8.0->autokeras) (3.2.2)

In [ ]:
import pandas as pd
import tensorflow as tf
import autokeras as ak

In [ ]:
training_features_data = pd.read_csv("/content/train.csv", sep=',')
test_features_data = pd.read_csv('/content/test.csv',sep=',')

## Train

In [ ]:
training_features_data=training_features_data.set_index('id')

In [ ]:
training_set_labels = training_features_data[['DC201']]

In [ ]:
training_features_data

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
id,,,,,,,,,,,,,,,,,,,,,
1,11,2,16.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,2.0,1,12.0,60.0,Layak Minum
2,11,2,31.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,2,31.0,70.0,Layak Minum
3,11,2,12.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,4,11.0,75.0,Layak Minum
6,11,2,12.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,2.0,NaN,1.0,0.0,1.0,1,11.0,85.0,Layak Minum
7,11,2,12.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2,11.0,65.0,Layak Minum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47958,94,1,17.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,NaN,0.0,0.0,0.0,1,21.0,9.0,Layak Minum
47959,94,1,12.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,2,11.0,12.0,Layak Minum
47961,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1,11.0,48.0,Layak Minum
47962,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,2,11.0,39.0,Layak Minum
47963,94,1,12.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,3,11.0,40.0,Layak Minum

In [ ]:
import pandas as pd

# perform one-hot encoding on the 'DC201' column
one_hot_encoded = pd.get_dummies(training_set_labels)

# join the one-hot encoded dataframe with the original training_set_labels dataframe
training_set_labels_ohe = pd.concat([training_set_labels, one_hot_encoded], axis=1)

# drop the original 'DC201' column
training_set_labels_ohe.drop('DC201', axis=1, inplace=True)
training_set_labels_ohe.drop('DC201_Tidak Layak Minum', axis=1, inplace=True)
training_set_labels_ohe.rename(columns={'DC201_Layak Minum': 'DC201'}, inplace=True)

# print the resulting dataframe with one-hot encoded features
print(training_set_labels_ohe.head())

    DC201
id
1       1
2       1
3       1
6       1
7       1

In [ ]:
training_set_labels=training_set_labels_ohe

In [ ]:
training_set_labels=training_set_labels.loc[:, 'DC201'].values
training_features_data = training_features_data.loc[:, ~training_features_data.columns.isin(['DC201'])]
test_features_data=test_features_data.set_index('id')

In [ ]:
DC024_mapped = {
    11 : "aceh",
    12 : "north sumatera",
    13 : "west sumatera",
    14 : "riau",
    15 : "jambi",
    16 : "south sumatera",
    17 : "bengkulu",
    18 : "lampung",
    19 : "bangka belitung",
    21 : "riau islands",
    31 : "jakarta",
    32 : "west java",
    33 : "central java",
    34 : "yogyakarta",
    35 : "east java",
    36 : "banten",
    51 : "bali",
    52 : "west nusa tenggara",
    53 : "east nusa tenggara",
    61 : "west kalimantan",
    62 : "central kalimantan",
    63 : "south kalimantan",
    64 : "east kalimantan",
    65 : "north kalimantan",
    71 : "north sulawesi",
    72 : "central sulawesi",
    73 : "south sulawesi",
    74 : "southeast sulawesi",
    75 : "gorontalo",
    76 : "west sulawesi",
    81 : "maluku",	
    82 : "north maluku",
    91 : "west papua",
    94 : "papua"
}
DC205_mapped = {
    -1 : "None DC205",
    10 : "flush toilet",
    11 : "flush to piped sewer system",
    12 : "flush to septic tank",
    13 : "flush to pit latrine",
    14 : "flush to somewhere else",
    15 : "flush, don't know where",
    16 : "flush with no septic tank",
    17 : "flush toilet : shared / public",
    20 : "pit toilet latrine",
    21 : "ventilated improved pit latrine (VIP)",
    22 : "pit latrine with slab",
    23 : "pit latrine without slab/open pit",
    30 : "no facility",
    31 : "no facility/bush/field/river/ beach/ pond/pool",
    41 : "composting toilet",
    42 : "bucket toilet",
    43 : "hanging toilet/latrine",
    96 : "other DC205"
}
DC213_mapped = {
    -1 : "None DC213",
    10 : "natural DC213",
    11 : "earth/sand DC213",
    12 : "dung DC213",
    20 : "rudimentary DC213",
    21 : "wood planks DC213",
    22 : "palm/bamboo DC213",
    30 : "finished DC213",
    31 : "parquet or polished wood DC213",
    32 : "vinyl or asphalt strips DC213",
    33 : "ceramic/marble/granite DC213",
    34 : "floor tiles/teraso DC213",
    35 : "cement/red bricks DC213",
    36 : "carpet DC213",
    96 : "other DC213"
}
DC214_mapped = {
    -1 : "None DC214",
    10 : "natural DC214",
    12 : "thatch/palm leaf DC214",
    13 : "sod DC214",
    20 : "rudimentary DC214",
    21 : "rustic mat DC214",
    22 : "palm/bamboo DC214",
    23 : "wood planks DC214",
    30 : "finished DC214",
    31 : "roofing DC214",
    32 : "asbestos DC214",
    33 : "tile DC214",
    34 : "concrete DC214",
    35 : "metal tile DC214",
    36 : "roofing shingles DC214",
    96 : "other DC214"
}
DC215_mapped = {
    -1 : "None DC215",
    10 : "natural DC215",
    12 : "thatch/palm leaf DC215",
    13 : "sod DC215",
    20 : "rudimentary DC215",
    21 : "rustic mat DC215",
    22 : "palm/bamboo DC215",
    23 : "wood planks DC215",
    30 : "finished DC215",
    31 : "roofing DC215",
    32 : "asbestos DC215",
    33 : "tile DC215",
    34 : "concrete DC215",
    35 : "metal tile DC215",
    36 : "roofing shingles DC215",
    96 : "other DC215"
}
DC226_mapped = {
    -1 : "None DC226",
    1 : "electricity",
    2 : "lpg",	
    3 : "natural gas",	
    4 : "biogas",
    5 : "kerosene",
    6 : "coal, lignite",
    7 : "charcoal",
    8 : "wood",
    9 : "straw/shrubs/grass",
    10 : "agricultural crop",
    11 : "animal dung",
    95 : "no food cooked in house",
    96 : "other DC226"
}
DC230a_mapped = {
    -1 : "None DC230a",
    1 : "observed, fixed place",
    2 : "observed, mobile place",
    3 : "not observed: not in dwelling",
    4 : "not observed: no permission to see",
    5 : "not observed: other reason"
}
DC235_mapped = {
    -1 : "None DC235",
    1 : "in own dwelling",
    2 : "in own yard/plot",
    3 : "elsewhere"
}
DC241_mapped = {
    -1 : "None DC241",
    1 : "in the house",
    2 : "in a separate building",
    3 : "outdoors",
    6 : "other DC241"
}
DC252_mapped = {
    -1 : "None DC252",
    0 : "never",
    1 : "daily",
    2 : "weekly",
    3 : "monthly",
    4 : "less than once a month"
}
DC109_mapped = {
    -1 : "None DC109",
    11 : "private: with septic tank",
    12 : "private: with no septic tank",
    21 : "shared/public",
    31 : "river/stream/creek",
    32 : "beach",
    33 : "pool/ponds",
    41 : "pit",
    51 : "yard/bush/forest",
    96 : "other DC109"
}
separated_cols = ['DC024', 'DC205', 'DC213', 'DC214', 'DC215',
       'DC226', 'DC230a', 'DC235', 'DC241', 'DC252', 'DC109']
full_map = [DC024_mapped, DC205_mapped, DC213_mapped, DC214_mapped, DC215_mapped,
       DC226_mapped, DC230a_mapped, DC235_mapped, DC241_mapped, DC252_mapped, DC109_mapped]
for index, map in zip(separated_cols, full_map):
  training_features_data[index] = training_features_data[index].map(map)
training_features_data

<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)
<ipython-input-39-9029166be652>:173: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features_data[index] = training_features_data[index].map(map)

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
id,,,,,,,,,,,,,,,,,,,,,
1,aceh,2,flush with no septic tank,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,in the house,0.0,0.0,0.0,weekly,1,private: with no septic tank,60.0
2,aceh,2,no facility/bush/field/river/ beach/ pond/pool,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,in the house,0.0,1.0,1.0,daily,2,river/stream/creek,70.0
3,aceh,2,flush to septic tank,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,in the house,0.0,1.0,1.0,never,4,private: with septic tank,75.0
6,aceh,2,flush to septic tank,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,in a separate building,NaN,1.0,0.0,daily,1,private: with septic tank,85.0
7,aceh,2,flush to septic tank,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,in the house,0.0,0.0,1.0,never,2,private: with septic tank,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47958,papua,1,flush toilet : shared / public,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,outdoors,NaN,0.0,0.0,never,1,shared/public,9.0
47959,papua,1,flush to septic tank,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,in the house,1.0,0.0,0.0,never,2,private: with septic tank,12.0
47961,papua,1,flush to septic tank,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,in the house,1.0,0.0,1.0,daily,1,private: with septic tank,48.0
47962,papua,1,flush to septic tank,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,in the house,1.0,0.0,0.0,never,2,private: with septic tank,39.0
47963,papua,1,flush to septic tank,1.0,0.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,in the house,0.0,0.0,0.0,never,3,private: with septic tank,40.0

In [ ]:
training_features_data=training_features_data.fillna(training_features_data.mean())
training_features_data=training_features_data.fillna('out-of-category')

<ipython-input-40-21c95266ba6e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  training_features_data=training_features_data.fillna(training_features_data.mean())

In [ ]:
#encoding categorical features (str-->float)

from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

enc.fit(training_features_data)
training_features_data_arr=enc.transform(training_features_data)

col_names_list=training_features_data.columns
encoded_categorical_df=pd.DataFrame(training_features_data_arr, columns=col_names_list)

In [ ]:
#normalization(make all values bet. 0-1)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(encoded_categorical_df)
normalized_arr=scaler.transform(encoded_categorical_df)

normalized_df=pd.DataFrame(normalized_arr, columns=col_names_list)

# Test

In [ ]:
DC024_mapped = {
    11 : "aceh",
    12 : "north sumatera",
    13 : "west sumatera",
    14 : "riau",
    15 : "jambi",
    16 : "south sumatera",
    17 : "bengkulu",
    18 : "lampung",
    19 : "bangka belitung",
    21 : "riau islands",
    31 : "jakarta",
    32 : "west java",
    33 : "central java",
    34 : "yogyakarta",
    35 : "east java",
    36 : "banten",
    51 : "bali",
    52 : "west nusa tenggara",
    53 : "east nusa tenggara",
    61 : "west kalimantan",
    62 : "central kalimantan",
    63 : "south kalimantan",
    64 : "east kalimantan",
    65 : "north kalimantan",
    71 : "north sulawesi",
    72 : "central sulawesi",
    73 : "south sulawesi",
    74 : "southeast sulawesi",
    75 : "gorontalo",
    76 : "west sulawesi",
    81 : "maluku",	
    82 : "north maluku",
    91 : "west papua",
    94 : "papua"
}
DC205_mapped = {
    -1 : "None DC205",
    10 : "flush toilet",
    11 : "flush to piped sewer system",
    12 : "flush to septic tank",
    13 : "flush to pit latrine",
    14 : "flush to somewhere else",
    15 : "flush, don't know where",
    16 : "flush with no septic tank",
    17 : "flush toilet : shared / public",
    20 : "pit toilet latrine",
    21 : "ventilated improved pit latrine (VIP)",
    22 : "pit latrine with slab",
    23 : "pit latrine without slab/open pit",
    30 : "no facility",
    31 : "no facility/bush/field/river/ beach/ pond/pool",
    41 : "composting toilet",
    42 : "bucket toilet",
    43 : "hanging toilet/latrine",
    96 : "other DC205"
}
DC213_mapped = {
    -1 : "None DC213",
    10 : "natural DC213",
    11 : "earth/sand DC213",
    12 : "dung DC213",
    20 : "rudimentary DC213",
    21 : "wood planks DC213",
    22 : "palm/bamboo DC213",
    30 : "finished DC213",
    31 : "parquet or polished wood DC213",
    32 : "vinyl or asphalt strips DC213",
    33 : "ceramic/marble/granite DC213",
    34 : "floor tiles/teraso DC213",
    35 : "cement/red bricks DC213",
    36 : "carpet DC213",
    96 : "other DC213"
}
DC214_mapped = {
    -1 : "None DC214",
    10 : "natural DC214",
    12 : "thatch/palm leaf DC214",
    13 : "sod DC214",
    20 : "rudimentary DC214",
    21 : "rustic mat DC214",
    22 : "palm/bamboo DC214",
    23 : "wood planks DC214",
    30 : "finished DC214",
    31 : "roofing DC214",
    32 : "asbestos DC214",
    33 : "tile DC214",
    34 : "concrete DC214",
    35 : "metal tile DC214",
    36 : "roofing shingles DC214",
    96 : "other DC214"
}
DC215_mapped = {
    -1 : "None DC215",
    10 : "natural DC215",
    12 : "thatch/palm leaf DC215",
    13 : "sod DC215",
    20 : "rudimentary DC215",
    21 : "rustic mat DC215",
    22 : "palm/bamboo DC215",
    23 : "wood planks DC215",
    30 : "finished DC215",
    31 : "roofing DC215",
    32 : "asbestos DC215",
    33 : "tile DC215",
    34 : "concrete DC215",
    35 : "metal tile DC215",
    36 : "roofing shingles DC215",
    96 : "other DC215"
}
DC226_mapped = {
    -1 : "None DC226",
    1 : "electricity",
    2 : "lpg",	
    3 : "natural gas",	
    4 : "biogas",
    5 : "kerosene",
    6 : "coal, lignite",
    7 : "charcoal",
    8 : "wood",
    9 : "straw/shrubs/grass",
    10 : "agricultural crop",
    11 : "animal dung",
    95 : "no food cooked in house",
    96 : "other DC226"
}
DC230a_mapped = {
    -1 : "None DC230a",
    1 : "observed, fixed place",
    2 : "observed, mobile place",
    3 : "not observed: not in dwelling",
    4 : "not observed: no permission to see",
    5 : "not observed: other reason"
}
DC235_mapped = {
    -1 : "None DC235",
    1 : "in own dwelling",
    2 : "in own yard/plot",
    3 : "elsewhere"
}
DC241_mapped = {
    -1 : "None DC241",
    1 : "in the house",
    2 : "in a separate building",
    3 : "outdoors",
    6 : "other DC241"
}
DC252_mapped = {
    -1 : "None DC252",
    0 : "never",
    1 : "daily",
    2 : "weekly",
    3 : "monthly",
    4 : "less than once a month"
}
DC109_mapped = {
    -1 : "None DC109",
    11 : "private: with septic tank",
    12 : "private: with no septic tank",
    21 : "shared/public",
    31 : "river/stream/creek",
    32 : "beach",
    33 : "pool/ponds",
    41 : "pit",
    51 : "yard/bush/forest",
    96 : "other DC109"
}
separated_cols = ['DC024', 'DC205', 'DC213', 'DC214', 'DC215',
       'DC226', 'DC230a', 'DC235', 'DC241', 'DC252', 'DC109']
full_map = [DC024_mapped, DC205_mapped, DC213_mapped, DC214_mapped, DC215_mapped,
       DC226_mapped, DC230a_mapped, DC235_mapped, DC241_mapped, DC252_mapped, DC109_mapped]
for index, map in zip(separated_cols, full_map):
  test_features_data[index] = test_features_data[index].map(map)
test_features_data

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
id,,,,,,,,,,,,,,,,,,,,,
26718,east java,2,flush toilet : shared / public,1,0,1,0,1,1,0,...,0,0,in the house,1,1,1,daily,3,shared/public,52
26802,east java,1,flush to septic tank,1,1,1,1,0,1,0,...,0,0,in the house,1,0,0,daily,2,private: with septic tank,18
41302,southeast sulawesi,2,flush to septic tank,1,0,1,1,1,1,0,...,0,0,in the house,0,0,1,less than once a month,5,private: with septic tank,78
38698,central sulawesi,1,flush to septic tank,1,1,0,0,0,0,1,...,0,0,in the house,0,1,0,never,1,private: with septic tank,20
44257,west sulawesi,2,flush to septic tank,1,0,1,0,0,1,0,...,0,0,in the house,1,1,1,daily,3,private: with septic tank,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36943,north kalimantan,2,flush to septic tank,1,0,1,0,0,1,1,...,0,0,in the house,0,0,0,never,4,private: with septic tank,70
33415,west kalimantan,2,flush to septic tank,1,0,1,1,0,1,0,...,0,1,in the house,1,1,0,never,4,private: with septic tank,120
41998,southeast sulawesi,1,flush to septic tank,1,1,1,1,0,1,0,...,0,0,in the house,1,0,0,daily,2,private: with septic tank,72
41567,southeast sulawesi,2,no facility/bush/field/river/ beach/ pond/pool,0,0,0,0,0,1,0,...,0,0,in the house,0,0,1,daily,1,yard/bush/forest,9
45296,maluku,1,flush to septic tank,1,0,1,1,0,0,0,...,0,0,in the house,1,0,0,daily,2,private: with septic tank,96

In [ ]:
#eliminate null values

#for float types
test_features_data=test_features_data.fillna(test_features_data.mean())

#for string types
test_features_data=test_features_data.fillna('out-of-category')

<ipython-input-44-6d8dfad35418>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  test_features_data=test_features_data.fillna(test_features_data.mean())

In [ ]:
#encoding categorical features (str-->float)

from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

enc.fit(test_features_data)
test_features_data_arr=enc.transform(test_features_data)

col_names_list=test_features_data.columns
test_encoded_categorical_df=pd.DataFrame(test_features_data_arr, columns=col_names_list)

In [ ]:
#normalization(bet. 0-1)

#using minmax scaler(look up)
test_normalized_arr=scaler.transform(test_encoded_categorical_df)
test_normalized_df=pd.DataFrame(test_normalized_arr, columns=col_names_list)

In [ ]:
# split df to X and Y
y = training_set_labels
X = normalized_df

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split# split data into 80-20 for training set / test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y)

In [ ]:
# Initialize the structured data classifier.
clf = ak.StructuredDataClassifier(
    overwrite=True, max_trials=5
)  # It tries 3 different models.
clf.fit(
    X_train,
    y_train,
    # Split the training data and use the last 15% as validation data.
    validation_split=0.15,
    epochs=100,
)

Trial 5 Complete [00h 02m 52s]
val_accuracy: 0.908329427242279

Best val_accuracy So Far: 0.912284791469574
Total elapsed time: 00h 17m 02s
Epoch 1/100
900/900 [==============================] - 7s 6ms/step - loss: 0.2859 - accuracy: 0.8875
Epoch 2/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2378 - accuracy: 0.9024
Epoch 3/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2302 - accuracy: 0.9042
Epoch 4/100
900/900 [==============================] - 5s 6ms/step - loss: 0.2252 - accuracy: 0.9058
Epoch 5/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2212 - accuracy: 0.9074
Epoch 6/100
900/900 [==============================] - 5s 6ms/step - loss: 0.2181 - accuracy: 0.9089
Epoch 7/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2151 - accuracy: 0.9092
Epoch 8/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2120 - accuracy: 0.9110
Epoch 9/100
900/900 [==============================] - 5s 5ms/step - loss: 0.2095 - accuracy: 0.9111
Epoch 10/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2071 - accuracy: 0.9121
Epoch 11/100
900/900 [==============================] - 5s 5ms/step - loss: 0.2050 - accuracy: 0.9130
Epoch 12/100
900/900 [==============================] - 5s 5ms/step - loss: 0.2030 - accuracy: 0.9140
Epoch 13/100
900/900 [==============================] - 4s 4ms/step - loss: 0.2012 - accuracy: 0.9142
Epoch 14/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1997 - accuracy: 0.9145
Epoch 15/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1982 - accuracy: 0.9153
Epoch 16/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1970 - accuracy: 0.9159
Epoch 17/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1956 - accuracy: 0.9165
Epoch 18/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1946 - accuracy: 0.9172
Epoch 19/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1932 - accuracy: 0.9175
Epoch 20/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1921 - accuracy: 0.9182
Epoch 21/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1909 - accuracy: 0.9189
Epoch 22/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1899 - accuracy: 0.9191
Epoch 23/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1888 - accuracy: 0.9200
Epoch 24/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1879 - accuracy: 0.9202
Epoch 25/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1870 - accuracy: 0.9198
Epoch 26/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1860 - accuracy: 0.9207
Epoch 27/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1851 - accuracy: 0.9218
Epoch 28/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1841 - accuracy: 0.9227
Epoch 29/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1836 - accuracy: 0.9229
Epoch 30/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1824 - accuracy: 0.9232
Epoch 31/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1816 - accuracy: 0.9238
Epoch 32/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1806 - accuracy: 0.9242
Epoch 33/100
900/900 [==============================] - 4s 4ms/step - loss: 0.1799 - accuracy: 0.9241
Epoch 34/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1788 - accuracy: 0.9248
Epoch 35/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1780 - accuracy: 0.9256
Epoch 36/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1774 - accuracy: 0.9261
Epoch 37/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1765 - accuracy: 0.9266
Epoch 38/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1758 - accuracy: 0.9266
Epoch 39/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1753 - accuracy: 0.9269
Epoch 40/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1746 - accuracy: 0.9271
Epoch 41/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1740 - accuracy: 0.9274
Epoch 42/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1733 - accuracy: 0.9272
Epoch 43/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1727 - accuracy: 0.9273
Epoch 44/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1722 - accuracy: 0.9277
Epoch 45/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1715 - accuracy: 0.9279
Epoch 46/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1711 - accuracy: 0.9279
Epoch 47/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1707 - accuracy: 0.9284
Epoch 48/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1700 - accuracy: 0.9280
Epoch 49/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1696 - accuracy: 0.9285
Epoch 50/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1690 - accuracy: 0.9290
Epoch 51/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1688 - accuracy: 0.9288
Epoch 52/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1681 - accuracy: 0.9295
Epoch 53/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1675 - accuracy: 0.9301
Epoch 54/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1672 - accuracy: 0.9300
Epoch 55/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1666 - accuracy: 0.9302
Epoch 56/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1662 - accuracy: 0.9308
Epoch 57/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1656 - accuracy: 0.9312
Epoch 58/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1652 - accuracy: 0.9311
Epoch 59/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1647 - accuracy: 0.9311
Epoch 60/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1646 - accuracy: 0.9315
Epoch 61/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1642 - accuracy: 0.9316
Epoch 62/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1637 - accuracy: 0.9315
Epoch 63/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1633 - accuracy: 0.9323
Epoch 64/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1630 - accuracy: 0.9328
Epoch 65/100
900/900 [==============================] - 6s 7ms/step - loss: 0.1629 - accuracy: 0.9324
Epoch 66/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1623 - accuracy: 0.9330
Epoch 67/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1621 - accuracy: 0.9330
Epoch 68/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1616 - accuracy: 0.9327
Epoch 69/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1614 - accuracy: 0.9330
Epoch 70/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1609 - accuracy: 0.9333
Epoch 71/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1608 - accuracy: 0.9335
Epoch 72/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1604 - accuracy: 0.9342
Epoch 73/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1602 - accuracy: 0.9337
Epoch 74/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1599 - accuracy: 0.9340
Epoch 75/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1596 - accuracy: 0.9339
Epoch 76/100
900/900 [==============================] - 6s 7ms/step - loss: 0.1592 - accuracy: 0.9342
Epoch 77/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1591 - accuracy: 0.9337
Epoch 78/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1585 - accuracy: 0.9349
Epoch 79/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1582 - accuracy: 0.9340
Epoch 80/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1579 - accuracy: 0.9345
Epoch 81/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1577 - accuracy: 0.9340
Epoch 82/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1573 - accuracy: 0.9338
Epoch 83/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1568 - accuracy: 0.9344
Epoch 84/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1566 - accuracy: 0.9349
Epoch 85/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1563 - accuracy: 0.9346
Epoch 86/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1561 - accuracy: 0.9350
Epoch 87/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1556 - accuracy: 0.9359
Epoch 88/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1555 - accuracy: 0.9362
Epoch 89/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1551 - accuracy: 0.9361
Epoch 90/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1549 - accuracy: 0.9359
Epoch 91/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1546 - accuracy: 0.9366
Epoch 92/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1544 - accuracy: 0.9363
Epoch 93/100
900/900 [==============================] - 6s 7ms/step - loss: 0.1540 - accuracy: 0.9362
Epoch 94/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1537 - accuracy: 0.9369
Epoch 95/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1534 - accuracy: 0.9366
Epoch 96/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1531 - accuracy: 0.9367
Epoch 97/100
900/900 [==============================] - 4s 5ms/step - loss: 0.1526 - accuracy: 0.9375
Epoch 98/100
900/900 [==============================] - 6s 6ms/step - loss: 0.1527 - accuracy: 0.9375
Epoch 99/100
900/900 [==============================] - 5s 5ms/step - loss: 0.1523 - accuracy: 0.9374
Epoch 100/100
900/900 [==============================] - 5s 6ms/step - loss: 0.1520 - accuracy: 0.9377

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

In [ ]:
model = clf.export_model()
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 38)]              0

 multi_category_encoding (Mu  (None, 38)               0
 ltiCategoryEncoding)

 normalization (Normalizatio  (None, 38)               77
 n)

 dense (Dense)               (None, 32)                1248

 batch_normalization (BatchN  (None, 32)               128
 ormalization)

 re_lu (ReLU)                (None, 32)                0

 dense_1 (Dense)             (None, 32)                1056

 batch_normalization_1 (Batc  (None, 32)               128
 hNormalization)

 re_lu_1 (ReLU)              (None, 32)                0

 dense_2 (Dense)             (None, 1)                 33

 classification_head_1 (Acti  (None, 1)                0
 vation)

=================================================================
Total params: 2,670
Trainable params: 2,465
Non-trainable params: 205
_________________________________________________________________

In [ ]:
# Predict with the best model.
predicted_y = clf.predict(X_test)

225/225 [==============================] - 1s 4ms/step
225/225 [==============================] - 1s 3ms/step

In [ ]:
# Evaluate the best model with testing data.
print(clf.evaluate(X_test, y_test.reshape(-1, 1)))

In [ ]:
predicted=clf.predict(test_features_data)

UnimplementedError: ignored

In [ ]:
predicted

In [ ]:
submission = pred_test[["id", "prediction_label"]].rename(columns={'prediction_label': 'DC201'})
submission.loc[submission['DC201'] == 0, 'DC201'] = "Tidak Layak Minum"
submission.loc[submission['DC201'] == 1, 'DC201'] = "Layak Minum"
submission